---
title: "data_preprocess_nodiet_reg_basic"
author: "yuntian"
date: '2022-05-17'
output: html_document
---

## Package loading
```{r}

## tidyverse
if(!require(tidyverse)){
    install.packages("tidyverse")
    library(tidyverse)
} else {
  library(tidyverse)
}

## haven
if(!require(haven)){
    install.packages("haven")
    library(haven)
} else {
  library(haven)
}


## dplyr
if(!require(dplyr)){
    install.packages("dplyr")
    library(dplyr)
} else {
  library(dplyr)
}



## survey
if(!require(survey)){
    install.packages("survey")
    library(survey)
} else {
  library(survey)
}


## to dummy
if(!require(fastDummies)){
    install.packages("fastDummies")
    library(fastDummies)
} else {
  library(fastDummies)
}


## caret
if(!require(caret)){
    install.packages("caret")
    library(caret)
} else {
  library(caret)
}

wd_path <- "./data/"

```

## read data

```{r}


data <- read.csv(paste0(wd_path, 'data_vo2max_all.csv'))
data4pred_16yrs <- read.csv(paste0(wd_path, 'data16_vo2max_all_allage.csv'))

for (var in colnames(data)){
  if(is.numeric(data[,var])){
    hist(data[,var], breaks = 20, main=var)
  }
}
```




## transform and select varaiables
```{r}

data_transform = data %>%
  mutate(
    age_log = log(age),
    ALT = ifelse(ALT<=200,ALT,200),
    AST = ifelse(AST<=200,AST,200),
    GLU = ifelse(GLU<=300,GLU,300),
    LDH = ifelse(LDH<=400,LDH,400),
    HBA1C = ifelse(HBA1C<=12,HBA1C,12),
    albuminuria = ifelse(albuminuria<=100,albuminuria,100),
    CREATININE = ifelse(CREATININE<=2,CREATININE,2),
    DI_mean = ifelse(DI_mean>=20,DI_mean,20),
    TWMT_log = log(ifelse(TWMT<=4000,TWMT,4000)+1),
    walk_bike = ifelse(walk_bicycle_times_wk<=7,walk_bicycle_times_wk,7),
    walk_bike_binary = ifelse(walk_bike>0,1,0),
    calorie_diet_log = log(CALORIE_DIET+1),
    protein_diet_log = log(PROTEIN_DIET+1),
    carb_diet_log =log(CARB_DIET+1),
    fat_diet_log = log(FAT_DIET+1),
    sfat_diet_log = log(SFAT_DIET+1),
    mfat_diet_log = log(MFAT_DIET+1),
    pfat_diet_log = log(PFAT__DIET+1),
    chol_diet_log = log(CHOL_DIET+1),
    fiber_diet_log = log(FIBE_DIET+1),
    folate_diet_log = log(FOLATE_DIET+1),
    calc_diet_log = log(CALC_DIET+1),
    iron_diet_log = log(IRON_DIET+1),
    sodi_diet_log = log(SODI_DIET+1),
    pota_diet_log = log(POTA_DIET+1),
    caff_diet_log = log(CAFF_DIET+1),
    alco_diet_log = log(ALCO_DIET+1),
    totalwater_log = log(TOTWATER+1),
    vb1_diet_log = log(VB1_DIET+1),
    vb2_diet_log = log(VB2_DIET+1),
    vb6_diet_log = log(VB6_DIET+1),
    vb12_diet_log = log(VB12_DIET+1),
    vc_diet_log = log(VC_DIET+1),
    ve_diet_log = log(VE_DIET+1),
    ts040_diest_log = log(TS040+1),
    ts060_diest_log = log(TS060+1),
    ts080_diest_log = log(TS080+1),
    ts100_diest_log = log(TS100+1),
    ts120_diest_log = log(TS120+1),
    ts140_diest_log = log(TS140+1),
    ts160_diest_log = log(TS160+1),
    ts180_diest_log = log(TS180+1),
    tm161_diest_log = log(TM161+1),
    tm181_diest_log = log(TM181+1),
    tm201_diest_log = log(TM201+1),
    tm221_diest_log = log(TM221+1),
    tP182_diest_log = log(TP182+1),
    tP183_diest_log = log(TP183+1),
    tP184_diest_log = log(TP184+1),
    tP204_diest_log = log(TP204+1),
    tP205_diest_log = log(TP205+1),
    tP225_diest_log = log(TP225+1),
    tP226_diest_log = log(TP226+1)
  )

## for prediction
data4pred_16yrs_transform = data4pred_16yrs %>%
  mutate(age_log = log(age),
    ALT = ifelse(ALT<=200,ALT,200),
    AST = ifelse(AST<=200,AST,200),
    GLU = ifelse(GLU<=300,GLU,300),
    LDH = ifelse(LDH<=400,LDH,400),
    HBA1C = ifelse(HBA1C<=12,HBA1C,12),
    albuminuria = ifelse(albuminuria<=100,albuminuria,100),
    CREATININE = ifelse(CREATININE<=2,CREATININE,2),
    DI_mean = ifelse(DI_mean>=20,DI_mean,20),
    TWMT_log = log(ifelse(TWMT<=4000,TWMT,4000)+1),
    walk_bike = ifelse(walk_bicycle_times_wk<=7,walk_bicycle_times_wk,7),
    walk_bike_binary = ifelse(walk_bike>0,1,0))


colnames(data_transform)

all_variables <- c("age","gender","race_ethn","educ","marital_status","INDFMPIR","family_income","health_insurance",
                   "employment_status","smoking_status","agec_l20","agec_20_29","agec_30_39","agec_40_49","htn_history",
                   "diab_history","WTMEC2YR","WTINT2YR","ALT","AST","BUN","GLU","LDH","CHOL","TOTPRO","POTAS","SODI",
                   "CHL","HBA1C","CREATININE","BILIRUBIN","IRON","CALCIUM","BICARBONATE","SY_mean","DI_mean","BMXBMI",
                   "BMXWAIST","BPXPLS","BMXWT","BMXHT","alcohol_intake","TWMT","physical_activity","WT_DIFF_KG","albuminuria",
                   "lwlstyr","exerc2lwlastyr","walk_bicycle_times_wk","CVDESVO2","ARM_PF","ARM_BMD",
                   "ARM_LEAN","LEG_PF","LEG_BMD","LEG_LEAN", "TR_PF","TR_BMD","TR_LEAN","TOTAL_PF","TOTAL_BMD","TOTAL_LEAN",
                   "IS_WEEKEND_DIET","COMPARE_USUAL","COMPARE_LESS","COMPARE_MORE","CALORIE_DIET","PROTEIN_DIET", "CARB_DIET",
                   "FAT_DIET","SFAT_DIET","MFAT_DIET","PFAT__DIET","CHOL_DIET","FIBE_DIET","VB1_DIET","VB2_DIET","NIAC_DIET",
                   "VB6_DIET","FOLATE_DIET","VB12_DIET","VC_DIET","VE_DIET","CALC_DIET","PHOS_DIET","MG_DIET","IRON_DIET",
                   "ZINC_DIET","COPP_DIET","SODI_DIET","POTA_DIET","SELE_DIET","CAFF_DIET","THEO_DIET","ALCO_DIET","MOIS_DIET",
                   "TOTWATER","TS040","TS060","TS080","TS100","TS120","TS140","TS160","TS180","TM161","TM181","TM201","TM221",
                   "TP182","TP183","TP184","TP204","TP205","TP225","TP226",
                   "age_log","TWMT_log","walk_bike","walk_bike_binary","calorie_diet_log","protein_diet_log","carb_diet_log",
                   "fat_diet_log","sfat_diet_log","mfat_diet_log","pfat_diet_log","chol_diet_log","fiber_diet_log",
                   "folate_diet_log","calc_diet_log","iron_diet_log","sodi_diet_log","pota_diet_log","caff_diet_log",
                   "alco_diet_log","totalwater_log","vb1_diet_log","vb2_diet_log","vb6_diet_log","vb12_diet_log",
                   "vc_diet_log","ve_diet_log", "ts040_diest_log","ts060_diest_log","ts080_diest_log","ts100_diest_log",
                   "ts120_diest_log","ts140_diest_log","ts160_diest_log","ts180_diest_log","tm161_diest_log","tm181_diest_log",
                   "tm201_diest_log","tm221_diest_log","tP182_diest_log","tP183_diest_log","tP184_diest_log","tP204_diest_log",
                   "tP205_diest_log","tP225_diest_log","tP226_diest_log")




selected_variables <- c("gender","race_ethn","educ","INDFMPIR","marital_status","family_income","health_insurance",
                   "employment_status","smoking_status","htn_history","age","CVDESVO2",
                   "ALT","AST","BUN","GLU","LDH","CHOL","TOTPRO","POTAS","SODI","albuminuria",
                   "CHL","HBA1C","CREATININE","BILIRUBIN","CALCIUM","BICARBONATE","SY_mean","DI_mean","BMXBMI",
                   "BMXWAIST","BPXPLS","BMXWT","BMXHT","alcohol_intake","physical_activity","WT_DIFF_KG",
                   "lwlstyr","exerc2lwlastyr","TWMT_log","walk_bike")


data_selected <- data_transform %>%
  dplyr::select(all_of(selected_variables))%>%
  mutate_if(., is.character, factor)

data4pred_16yrs_selected <- data4pred_16yrs_transform %>%
  dplyr::select(c('seqn',setdiff(selected_variables,'CVDESVO2')))%>%
  mutate_if(., is.character, factor)


```


## train test split
```{r}

set.seed(321)
num.all <- nrow(data_selected)
train.id <- sample(1:num.all,floor(0.8*num.all))

train_set <- data_selected[train.id, ]
test_set <- data_selected[-train.id, ]

X_train <- train_set %>% dplyr::select(-CVDESVO2)
y_train <- train_set$CVDESVO2

X_test <- test_set %>% dplyr::select(-CVDESVO2)
y_test <- test_set$CVDESVO2

X_pred <- data4pred_16yrs_selected %>% dplyr::select(-seqn)




##########################
## ALL with missingness ##
##########################

X_train_all_dummies <- fastDummies::dummy_cols(X_train, 
                                        remove_first_dummy = T,
                                        remove_selected_columns = T,
                                        ignore_na = T,
                                        split = '_')

X_test_all_dummies <- fastDummies::dummy_cols(X_test, 
                                        remove_first_dummy = T,
                                        remove_selected_columns = T,
                                        ignore_na = T,
                                        split = '_')

X_pred_all_dummies <- fastDummies::dummy_cols(X_pred, 
                                        remove_first_dummy = T,
                                        remove_selected_columns = T,
                                        ignore_na = T,
                                        split = '_')


train_all_dummies <- cbind(X_train_all_dummies, y_train)
test_all_dummies <- cbind(X_test_all_dummies, y_test)

write.csv(train_all_dummies,
          paste0(wd_path,'train_all_dummies.csv'),
          row.names = FALSE)
write.csv(test_all_dummies,
          paste0(wd_path,'test_all_dummies.csv'),
          row.names = FALSE)
write.csv(X_pred_all_dummies%>% mutate(seqn = data4pred_16yrs$seqn),
          paste0(wd_path,'X_pred_all_dummies.csv'),
          row.names = FALSE)

```
